version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: project-management-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./backend
      dockerfile: ${BACKEND_DOCKERFILE:-Dockerfile}
    container_name: project-management-api
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: projectmanagement
      DB_SSLMODE: disable
      JWT_KEY: your-super-secret-key-change-in-production
    ports:
      - "8080:8080"
    # Removing the volume mount that overwrites the compiled binary

  frontend:
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE:-Dockerfile}
    container_name: project-management-ui
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:${FRONTEND_PORT:-80}"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
